name: Trigger POST Request

on:
  workflow_dispatch:
    inputs:
      arg1:
        description: 'The current action run link'
        required: true
        default: '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.18'

    - name: Install dependencies (optional)
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt

    - name: Run the specified Python method
      run: |
        python src/run.py ${{ github.event.inputs.arg1 }}